In [2]:
import pandas as pd
import sys
import os

# Para poder importar desde src/
sys.path.append(os.path.abspath(".."))

from src.extract import extract

In [3]:
import importlib
import src.extract

importlib.reload(src.extract)

from src.extract import extract

catalog, web, products = extract()

print("Catalog:", catalog.shape)
print("Web:", web.shape)
print("Products:", products.shape)

Catalog: (6767, 7)
Web: (943, 7)
Products: (192, 7)

In [9]:
catalog.head()

   ID       INV              DATE    CATALOG   PCODE   QTY  custnum
0   1  107707.0   3/97/7 00:00:00     Sports  SP1000  1.00   1242.0
1   2  110633.0  3/97/25 00:00:00  Gardening  GD2200  1.00   1243.0
2   3  111155.0  3/97/28 00:00:00       Pets  PT1300  3.00   1244.0
3   4  126867.0  6/97/22 00:00:00       Toys  TY4100  1.00   1245.0
4   5  135872.0   8/97/8 00:00:00       Toys  TY1200  4.00   1246.0

In [10]:
web.head()

,ID,INV,DATE,CATALOG,PCODE,QTY,custnum
0,"1;2513000.00;""GD3200"";17/12/2000 00:00:00;""Gar...","Mr. Bob""",NaN,NaN,NaN,NaN,NaN
1,"2;2513000.00;""PT1400"";6/1/2001 00:00:00;""Pets""...","Mr. Bob""",NaN,NaN,NaN,NaN,NaN
2,"3;2513000.00;""PT2000"";6/1/2001 00:00:00;""Pet"";...","Mr. Bob""",NaN,NaN,NaN,NaN,NaN
3,"4;2513000.00;""PT2100"";6/1/2001 00:00:00;""Pets""...","Mr. Bob""",NaN,NaN,NaN,NaN,NaN
4,"5;2513000.00;""PT2OOO"";27/7/2000 00:00:00;""Pets...","Mr. Bob""",NaN,NaN,NaN,NaN,NaN

In [11]:
products.head()

,ID,TYPE,DESCRIP,PRICE,COST,PCODE,supplier
0,1,Database,Track-It-All,560.00,425.0,SW1005,"Software America, Inc."
1,2,Database,Omnibus,499.95,450.0,SW1207,Software America
2,3,Database,Balboa,499.00,300.0,SW3049,Software America
3,4,Financial,Stock Market Analyst,69.95,45.0,SW2842,Software America
4,5,Financial,Tax Relief (Version 10.40),77.95,54.5,SW4187,Software America

In [12]:
catalog.info()
web.info()
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 6767 entries, 0 to 6766
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       6767 non-null   int64
 1   INV      6767 non-null   float64
 2   DATE     6767 non-null   str
 3   CATALOG  6765 non-null   str
 4   PCODE    6767 non-null   str
 5   QTY      6761 non-null   str
 6   custnum  6766 non-null   float64
dtypes: float64(2), int64(1), str(4)
memory usage: 370.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       943 non-null    str
 1   INV      943 non-null    str
 2   DATE     0 non-null      float64
 3   CATALOG  0 non-null      float64
 4   PCODE    0 non-null      float64
 5   QTY      0 non-null      float64
 6   custnum  0 non-null      float64
dtypes: float64(5), str(2)
memory usage: 51.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        192 non-null    int64
 1   TYPE      192 non-null    str
 2   DESCRIP   192 non-null    str
 3   PRICE     192 non-null    float64
 4   COST      192 non-null    float64
 5   PCODE     192 non-null    str
 6   supplier  192 non-null    str
dtypes: float64(2), int64(1), str(4)
memory usage: 10.6 KB

In [13]:
catalog.describe()

                ID            INV       custnum
count  6767.000000    6767.000000  6.766000e+03
mean   3384.000000  160030.070785  4.022302e+06
std    1953.608968   40091.753729  4.698005e+06
min       1.000000   98689.000000  2.000000e+00
25%    1692.500000  128492.000000  1.964250e+03
50%    3384.000000  152391.000000  1.512000e+06
75%    5075.500000  192319.000000  8.020000e+06
max    6767.000000  243377.000000  1.378900e+07

In [14]:
web.describe()

       DATE  CATALOG  PCODE  QTY  custnum
count   0.0      0.0    0.0  0.0      0.0
mean    NaN      NaN    NaN  NaN      NaN
std     NaN      NaN    NaN  NaN      NaN
min     NaN      NaN    NaN  NaN      NaN
25%     NaN      NaN    NaN  NaN      NaN
50%     NaN      NaN    NaN  NaN      NaN
75%     NaN      NaN    NaN  NaN      NaN
max     NaN      NaN    NaN  NaN      NaN

In [15]:
products.describe()

               ID       PRICE        COST
count  192.000000  192.000000  192.000000
mean    96.500000   84.426771   55.593854
std     55.569776  117.442675   79.690758
min      1.000000    3.000000    1.000000
25%     48.750000   16.000000    9.227500
50%     96.500000   40.995000   22.150000
75%    144.250000   91.275000   63.892500
max    192.000000  600.000000  450.000000

In [17]:
catalog["QTY"] = pd.to_numeric(catalog["QTY"], errors="coerce")
print("QTY var:", catalog["QTY"].var())
print("QTY min/max:", catalog["QTY"].min(), catalog["QTY"].max())

QTY var: 271.21046546747664
QTY min/max: 1.0 1353.0

In [18]:
catalog["CATALOG"].value_counts()

CATALOG
Sports          1851
Pets            1671
Toys            1309
Gardening        933
Software         506
Collectibles     150
Sport             59
Toy               52
Softwares         31
Tosy              27
Softwars          25
Collectible       23
Sporst            23
Spots             19
Pest              18
Softwar           15
GARDENING         14
Gardning          11
Pet                9
Colectibles        6
Tots               4
Pats               4
Collectables       2
Prts               2
 ,TY4400"          1
Name: count, dtype: int64

In [19]:
# Tipos de datos
catalog.info()

# Estadísticos básicos
catalog.describe()

# Valores únicos (cardinalidad)
catalog.nunique()

# Ejemplo numérico
catalog["QTY"] = pd.to_numeric(catalog["QTY"], errors="coerce")
print("Varianza QTY:", catalog["QTY"].var())
print("Rango QTY:", catalog["QTY"].min(), catalog["QTY"].max())

<class 'pandas.DataFrame'>
RangeIndex: 6767 entries, 0 to 6766
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       6767 non-null   int64
 1   INV      6767 non-null   float64
 2   DATE     6767 non-null   str
 3   CATALOG  6765 non-null   str
 4   PCODE    6767 non-null   str
 5   QTY      6760 non-null   float64
 6   custnum  6766 non-null   float64
dtypes: float64(3), int64(1), str(3)
memory usage: 370.2 KB
Varianza QTY: 271.21046546747664
Rango QTY: 1.0 1353.0

In [22]:
# Promedio por tipo de catálogo
catalog.groupby("CATALOG")["QTY"].mean()

# Comportamiento por cliente
catalog.groupby("custnum")["QTY"].sum()

custnum
2.0            1.0
3.0            1.0
4.0            1.0
5.0            1.0
6.0            1.0
              ...
13532000.0    47.0
13664000.0    43.0
13682000.0    52.0
13782000.0    36.0
13789000.0    30.0
Name: QTY, Length: 3163, dtype: float64

In [4]:
# Valores nulos
print(catalog.isnull().sum())
print(web.isnull().sum())
print(products.isnull().sum())

# Tipos incorrectos (ejemplo QTY)
catalog["QTY"] = pd.to_numeric(catalog["QTY"], errors="coerce")
print(catalog[catalog["QTY"].isna()])

# Valores inválidos (ejemplo: negativos)
print(catalog[catalog["QTY"] < 0])

ID         0
INV        0
DATE       0
CATALOG    2
PCODE      0
QTY        6
custnum    1
dtype: int64
ID           0
INV          0
DATE       943
CATALOG    943
PCODE      943
QTY        943
custnum    943
dtype: int64
ID          0
TYPE        0
DESCRIP     0
PRICE       0
COST        0
PCODE       0
supplier    0
dtype: int64
        ID       INV               DATE       CATALOG   PCODE  QTY     custnum
410    411  167813.0    5/01/8 00:00:00      Software  SW4792  NaN      1611.0
1003  1004  189914.0   5/98/17 00:00:00     Gardening  GD3000  NaN      2145.0
1218  1219  136327.0   8/97/10 00:00:00          Toys  TY3700  NaN      2339.0
2886  2887  150958.0  10/97/26 00:00:00  Collectibles  CC1100  NaN       894.0
2900  2901  150958.0    2/01/2 00:00:00  Collectibles  CC1100  NaN      9054.0
5890  5891  150958.0  10/97/26 00:00:00  Collectibles  CC1100  NaN  11145000.0
5904  5905  150958.0    2/01/2 00:00:00  Collectibles  CC1100  NaN  11145000.0
Empty DataFrame
Columns: [ID, INV, DATE, CATALOG, PCODE, QTY, custnum]
Index: []

In [5]:
catalog.isna().sum()

ID         0
INV        0
DATE       0
CATALOG    2
PCODE      0
QTY        7
custnum    1
dtype: int64

In [6]:
# Duplicados
print(catalog.duplicated().sum())

# Strings sospechosos
print(catalog["CATALOG"].unique())

0
<StringArray>
[      'Sports',    'Gardening',         'Pets',         'Toys',
     'Software',          'Toy',     'Softwars',  'Colectibles',
 'Collectibles',  'Collectible',         'Pest',       'Sporst',
    ' ,TY4400"',    'Softwares',     'Gardning',         'Tots',
         'Tosy',        'Sport',          'Pet',      'Softwar',
    'GARDENING',        'Spots', 'Collectables',         'Prts',
         'Pats',            nan]
Length: 26, dtype: str

In [7]:
# Valores únicos
catalog["CATALOG"].value_counts()

# Normalización básica
catalog["CATALOG"] = catalog["CATALOG"].str.strip().str.upper()

# Ver cambios
catalog["CATALOG"].value_counts()

CATALOG
SPORTS          1851
PETS            1671
TOYS            1309
GARDENING        947
SOFTWARE         506
COLLECTIBLES     150
SPORT             59
TOY               52
SOFTWARES         31
TOSY              27
SOFTWARS          25
COLLECTIBLE       23
SPORST            23
SPOTS             19
PEST              18
SOFTWAR           15
GARDNING          11
PET                9
COLECTIBLES        6
TOTS               4
PATS               4
COLLECTABLES       2
PRTS               2
,TY4400"           1
Name: count, dtype: int64

In [8]:
# Detectar valores raros (ejemplo simple)
validos = ["A", "B", "C"]
catalog[~catalog["CATALOG"].isin(validos)]

        ID       INV               DATE    CATALOG   PCODE  QTY     custnum
0        1  107707.0    3/97/7 00:00:00     SPORTS  SP1000  1.0      1242.0
1        2  110633.0   3/97/25 00:00:00  GARDENING  GD2200  1.0      1243.0
2        3  111155.0   3/97/28 00:00:00       PETS  PT1300  3.0      1244.0
3        4  126867.0   6/97/22 00:00:00       TOYS  TY4100  1.0      1245.0
4        5  135872.0    8/97/8 00:00:00       TOYS  TY1200  4.0      1246.0
...    ...       ...                ...        ...     ...  ...         ...
6762  6763  138478.0  11/00/28 00:00:00       PETS  PT1000  1.0  13789000.0
6763  6764  138478.0  11/00/28 00:00:00       PETS  PT2100  1.0  13789000.0
6764  6765  138478.0  11/00/28 00:00:00       PETS  PT3300  1.0  13789000.0
6765  6766  151895.0    2/01/7 00:00:00       TOYS  TY4800  4.0  13789000.0
6766  6767  160208.0   3/01/23 00:00:00   SOFTWARE  SW8001  1.0  13789000.0

[6767 rows x 7 columns]